name: CoralGreif
options:
  bundleIdPrefix: com.coralgreif
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"

targets:
  CoralGreif:
    type: application
    platform: iOS
    sources:
      - CoralGreif
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.coralgreif.game
        INFOPLIST_FILE: CoralGreif/Info.plist
        SWIFT_VERSION: "5.0"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    info:
      path: CoralGreif/Info.plist
      properties:
        UILaunchStoryboardName: LaunchScreen
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait

  CoralGreifTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - CoralGreifTests
    dependencies:
      - target: CoralGreif
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.coralgreif.tests
        SWIFT_VERSION: "5.0"
        GENERATE_INFOPLIST_FILE: YES

schemes:
  CoralGreif:
    build:
      targets:
        CoralGreif: all
        CoralGreifTests: [test]
    test:
      targets:
        - CoralGreifTests
      gatherCoverageData: true
      coverageTargets:
        - CoralGreif
